### ISSUE TITLE
just encrypt

### ISSUE THREAD

**Issue by themaddoctor** [jwhart175/plain_sight#2]
Can you provide a way to just do the encryption without the hiding?
I tried the java file, and got exceptions.
Thanks.

**Comment by jwhart175** [comment]
This project is effectively unmaintained at this point.  I might do work on it for a compelling use case, but otherwise it's just a historical reference for me.

**Comment by jwhart175** [comment]
To "just encrypt" you can hop over to my cipherClock repository and utilize the html quickcrypt file found there.  I've removed the java src and jar to prevent confusion in this repository, and have updated the plain_sight encryption.  The only interface provided here now is the html version.
